import type { Deck } from "../lib/oblique.ts";

/**
 * The garden's starter deck: prompts in the garden's own words, for coming
 * at a thing from an angle. Brian Eno and Peter Schmidt's Oblique Strategies
 * is the form these borrow, and that deck is theirs — a reader who owns it
 * types the cards they want into a deck of their own beside this one. Dealt
 * alongside the reader's decks; struck from the shuffle in one press.
 */
export const STARTER: Deck = {
  slug: "starter",
  title: "the starter deck",
  own: false,
  cards: [
    "Turn it over. What is on the back?",
    "Say it to a child. Then to the person you least want to hear it.",
    "Remove the part you are proudest of.",
    "What would this look like if it were easy?",
    "Do the smallest version today.",
    "Take the thing you keep postponing and make it the first step.",
    "Which word are you leaning on? Take it out.",
    "Ask what the fallow bed knows.",
    "Make the constraint the subject.",
    "Do it in the wrong order.",
    "Who is not in the room? Speak as them.",
    "Repeat the last move until it breaks.",
    "Stop before it is finished.",
    "What is the boring answer? Do that.",
    "Change the unit: hours to days, words to sentences, one to many.",
    "Find the earliest version. Go back to it.",
    "Give it away.",
    "What would you do if no one would ever see it?",
    "What would you do if everyone would?",
    "Take the opposite as given. Now argue back.",
    "Leave a gap on purpose.",
    "Ask the body first.",
    "Which of your reasons are on the record? Use only those.",
    "Use only the hollow ones.",
    "Name what it costs. Now name what not doing it costs.",
    "Slow it down until you can see the joints.",
    "Speed it up until only the shape is left.",
    "Make it worse in one specific way.",
    "What did you believe about this a year ago?",
    "Borrow the structure of something unrelated.",
    "Delete the introduction.",
    "Do it by hand.",
    "Trust the mistake. Follow it for ten minutes.",
    "Say what you actually want. Then subtract the audience.",
    "Cut it in half. Which half do you keep?",
    "Wait one day. Draw again.",
    "Look for what is already finished.",
    "Do it as a gift to one named person.",
    "What am I protecting?",
    "Use the last thing you read.",
    "Write the ending first.",
    "Which rule are you obeying that no one set?",
    "What if this is the second draft?",
    "Let the material decide.",
    "Move it to a different room.",
    "Reverse the roles: you are the input.",
    "Find the number in it. Then remove the number.",
    "Leave it where you found it.",
    "Take out every adjective. See what is still standing.",
    "Make a list of what you will not do.",
    "Describe it without its name.",
    "Ask: whose problem is this, actually?",
    "Finish the sentence you keep starting.",
    "Do the part that needs no permission.",
    "Put a date on it and see what the date does.",
    "Read the margin. You already said something about this.",
  ],
};
