import type { Entry, Life } from "../lib/chronology.ts";

/**
 * Specimen A: a synthetic life, born 1988 and told at 38, carried over from
 * the standalone chronology instrument (pvcomms/chronology) where it was
 * written to exercise every mechanic. It is fiction. It is what a deployed
 * garden draws, since a server has no life to read, and what the desk can
 * show a reader who has set nothing down yet so the instrument is legible
 * before it is theirs. Nothing here is anyone's history.
 */
export const SPECIMEN_LIFE: Life = {
  born: "1988",
  horizon: "2028",
  scale: "clock",
  domains: [
    { id: "belonging", label: "Belonging", register: "inner" },
    { id: "taste", label: "Taste", register: "inner" },
    { id: "family", label: "Family", register: "outer" },
    { id: "body", label: "Body", register: "outer" },
    { id: "work", label: "Work", register: "outer" },
    { id: "money", label: "Money", register: "outer" },
  ],
};

const R = "2026-09-19";
const e = (
  slug: string,
  title: string,
  day: string,
  lane: string,
  looms: 1 | 2 | 3,
  note: string,
  extra: Partial<Entry> = {},
): Entry => ({
  slug,
  title,
  day,
  until: null,
  lane,
  looms,
  again: null,
  why: null,
  tags: [],
  stones: [],
  threads: [],
  recorded: R,
  note,
  ...extra,
});

export const SPECIMEN_ENTRIES: Entry[] = [
  e(
    "1993-fathers-long-silences-begin",
    "Father's long silences begin",
    "1993",
    "family",
    2,
    "He'd come home and just not be there. I learned to read the back of his head.",
  ),
  e(
    "1994-piano-lessons-praised-for-it",
    "Piano lessons; praised for it",
    "1994",
    "taste",
    1,
    "The first time anyone looked at me like I was worth looking at, I was playing.",
  ),
  e(
    "1996-moved-cities-lost-first-friends",
    "Moved cities; lost first friends",
    "1996-08",
    "belonging",
    3,
    "Nobody asked me. One day the house was boxes.",
  ),
  e(
    "1997-mother-ill-for-six-months",
    "Mother ill for six months",
    "1997-02",
    "family",
    3,
    "I made the toast. I was very good at being no trouble.",
    { until: "1997-08" },
  ),
  e(
    "2002-mocked-for-my-accent",
    "Mocked for my accent at the new school",
    "2002",
    "belonging",
    2,
    "I fixed the accent in a month. I fixed the rest of me later.",
  ),
  e(
    "2004-first-band-first-applause",
    "First band; first applause",
    "2004",
    "taste",
    2,
    "Three people clapped. I have been trying to get back to that room ever since.",
    { again: "yes" },
  ),
  e(
    "2008-father-loses-his-job",
    "Father loses his job",
    "2008-10",
    "money",
    3,
    "He didn't tell us for three months. I found the letter.",
  ),
  e(
    "2009-dropped-music-for-the-safe-degree",
    "Dropped music for the safe degree",
    "2009",
    "work",
    2,
    "It felt like adulthood. It was fear wearing a suit.",
    { again: "no" },
  ),
  e(
    "2011-first-job-overwork-praised",
    "First job; overwork praised",
    "2011-09",
    "work",
    2,
    "My manager said I was a machine. I took it as love.",
    { until: "2022-03" },
  ),
  e(
    "2015-partner-leaves",
    "Partner leaves: 'you're never here'",
    "2015",
    "belonging",
    3,
    "She wasn't wrong. I was at work even at dinner.",
  ),
  e(
    "2017-panic-attack-in-a-meeting",
    "Panic attack in a meeting",
    "2017-04-02",
    "body",
    3,
    "My body filed a complaint I hadn't read.",
  ),
  e(
    "2018-therapy-begins",
    "Therapy begins",
    "2018",
    "body",
    2,
    "First time I said the word 'afraid' out loud since I was nine.",
    { until: "now", again: "yes" },
  ),
  e(
    "2020-lockdown-alone-in-the-flat",
    "Lockdown, alone in the flat",
    "2020-03",
    "belonging",
    2,
    "Terrifying for a week. Then the quietest I've ever felt.",
  ),
  e(
    "2022-quit-went-freelance",
    "Quit; went freelance",
    "2022-03",
    "money",
    2,
    "I did the math for a year. Then I did it in a day.",
    { again: "yes" },
  ),
  e(
    "2024-piano-again-badly-happily",
    "Piano again, badly, happily",
    "2024",
    "taste",
    2,
    "I'm bad at it now. I don't care. That's new.",
    { again: "yes" },
  ),
  e(
    "2025-asked-my-father-about-the-job-loss",
    "Asked my father about the job loss",
    "2025-11-09",
    "family",
    3,
    "He said 'I thought I was protecting you.' I'd built a whole religion on his silence.",
  ),
  e(
    "2027-a-year-away",
    "A year away, somewhere I can't drive",
    "2027-03",
    "belonging",
    2,
    "Expected, not happened. I keep moving the month.",
    { until: "2028-03" },
  ),
  // the circumstances: what was simply the case, the weather of the era, the dated public events
  e(
    "1988-single-income-household",
    "Single-income household",
    "1988",
    "structure",
    2,
    "",
    { until: "2008" },
  ),
  e(
    "1988-first-generation-university-family",
    "First-generation university family",
    "1988",
    "structure",
    2,
    "",
    { until: "now" },
  ),
  e(
    "2001-dial-up-to-broadband",
    "Dial-up to broadband",
    "2001",
    "conjuncture",
    2,
    "",
    { until: "2004" },
  ),
  e("2008-recession", "Recession", "2008", "conjuncture", 2, "", {
    until: "2012",
  }),
  e(
    "2011-feed-era",
    "Feed era: smartphone and social",
    "2011",
    "conjuncture",
    2,
    "",
    { until: "now" },
  ),
  e("2020-pandemic", "Pandemic", "2020-03", "conjuncture", 2, "", {
    until: "2021-06",
  }),
  e(
    "2008-financial-crash",
    "Financial crash",
    "2008-09-15",
    "happening",
    2,
    "",
  ),
  e("2020-lockdown", "Lockdown", "2020-03-23", "happening", 2, ""),
  // the record's silence, named
  e(
    "1999-gap",
    "",
    "1999",
    "gap",
    2,
    "I don't remember those years. Nothing happened, I think.",
    { until: "2001", why: "no-record" },
  ),
];
